/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EditorPaquetes;

/**
 *
 * @author josed
 */
public class frmEditor extends javax.swing.JFrame {
    private ControladorPaquetes controlador = new ControladorPaquetes();
    private boolean guardado = true;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmEditor.class.getName());

    /**
     * Creates new form frmEditor
     */
    public frmEditor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        txtArchivo = new javax.swing.JMenu();
        txtAbrir = new javax.swing.JMenuItem();
        txtGuardar = new javax.swing.JMenuItem();
        txtSalir = new javax.swing.JMenuItem();
        txtEditar = new javax.swing.JMenu();
        txtCopiar = new javax.swing.JMenuItem();
        txtCortar = new javax.swing.JMenuItem();
        txtPegar = new javax.swing.JMenuItem();
        txtFuente = new javax.swing.JMenu();
        txtNegrita = new javax.swing.JMenuItem();
        txtCursiva = new javax.swing.JMenuItem();
        txtColor = new javax.swing.JMenu();
        txtFondo = new javax.swing.JMenuItem();
        txtLetra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTexto.setColumns(20);
        txtTexto.setRows(5);
        txtTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTextoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtTexto);

        txtArchivo.setText("Archivo");

        txtAbrir.setText("Abrir");
        txtAbrir.addActionListener(this::txtAbrirActionPerformed);
        txtArchivo.add(txtAbrir);

        txtGuardar.setText("Guardar");
        txtGuardar.addActionListener(this::txtGuardarActionPerformed);
        txtArchivo.add(txtGuardar);

        txtSalir.setText("Salir");
        txtSalir.addActionListener(this::txtSalirActionPerformed);
        txtArchivo.add(txtSalir);

        jMenuBar1.add(txtArchivo);

        txtEditar.setText("Editar");

        txtCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        txtCopiar.setText("Copiar");
        txtCopiar.addActionListener(this::txtCopiarActionPerformed);
        txtEditar.add(txtCopiar);

        txtCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        txtCortar.setText("Cortar");
        txtCortar.addActionListener(this::txtCortarActionPerformed);
        txtEditar.add(txtCortar);

        txtPegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        txtPegar.setText("Pegar");
        txtPegar.addActionListener(this::txtPegarActionPerformed);
        txtEditar.add(txtPegar);

        txtFuente.setText("Fuente");

        txtNegrita.setText("Negrita");
        txtNegrita.addActionListener(this::txtNegritaActionPerformed);
        txtFuente.add(txtNegrita);

        txtCursiva.setText("Cursiva");
        txtCursiva.addActionListener(this::txtCursivaActionPerformed);
        txtFuente.add(txtCursiva);

        txtEditar.add(txtFuente);

        txtColor.setText("Color");

        txtFondo.setText("Fondo");
        txtFondo.addActionListener(this::txtFondoActionPerformed);
        txtColor.add(txtFondo);

        txtLetra.setText("Letra");
        txtLetra.addActionListener(this::txtLetraActionPerformed);
        txtColor.add(txtLetra);

        txtEditar.add(txtColor);

        jMenuBar1.add(txtEditar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardarActionPerformed
       controlador.guardar(this);
       guardado= true;
    }//GEN-LAST:event_txtGuardarActionPerformed

    private void txtCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCortarActionPerformed
        controlador.cortar(txtTexto);
    }//GEN-LAST:event_txtCortarActionPerformed

    private void txtPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPegarActionPerformed
        controlador.pegar(txtTexto);
    }//GEN-LAST:event_txtPegarActionPerformed

    private void txtAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAbrirActionPerformed
       controlador.abrir(this, txtTexto);
       guardado = true;
    }//GEN-LAST:event_txtAbrirActionPerformed

    private void txtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalirActionPerformed
        if(guardado){
            dispose();
        }else{
            if(controlador.confirmarSalida(this)){
                dispose();
            }
        }
    }//GEN-LAST:event_txtSalirActionPerformed

    private void txtCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCopiarActionPerformed
       controlador.copiar(txtTexto);
    }//GEN-LAST:event_txtCopiarActionPerformed

    private void txtNegritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNegritaActionPerformed
        controlador.negrita(txtTexto);
    }//GEN-LAST:event_txtNegritaActionPerformed

    private void txtCursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursivaActionPerformed
        controlador.cursiva(txtTexto);
    }//GEN-LAST:event_txtCursivaActionPerformed

    private void txtFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFondoActionPerformed
        controlador.colorFondo(this, txtTexto);
    }//GEN-LAST:event_txtFondoActionPerformed

    private void txtLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLetraActionPerformed
        controlador.colorLetra(this, txtTexto);
    }//GEN-LAST:event_txtLetraActionPerformed

    private void txtTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTextoKeyTyped
        guardado = false;
       //"identificar que hay cambios sin guardar
    }//GEN-LAST:event_txtTextoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmEditor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem txtAbrir;
    private javax.swing.JMenu txtArchivo;
    private javax.swing.JMenu txtColor;
    private javax.swing.JMenuItem txtCopiar;
    private javax.swing.JMenuItem txtCortar;
    private javax.swing.JMenuItem txtCursiva;
    private javax.swing.JMenu txtEditar;
    private javax.swing.JMenuItem txtFondo;
    private javax.swing.JMenu txtFuente;
    private javax.swing.JMenuItem txtGuardar;
    private javax.swing.JMenuItem txtLetra;
    private javax.swing.JMenuItem txtNegrita;
    private javax.swing.JMenuItem txtPegar;
    private javax.swing.JMenuItem txtSalir;
    private javax.swing.JTextArea txtTexto;
    // End of variables declaration//GEN-END:variables
}
